global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins_job'
    static_configs:
      - targets: ['localhost:8080']  
    metrics_path: '/prometheus'
    scheme: 'https'
    basic_auth:
      username: 'admin'
      password: '1192daa07779d83ffd0d2e4ef933805b4f'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
